[features]
seeds = false
skip-lint = false
[programs.devnet]
new_project = "3dY4fgav22wK1PvFY6BadcAqX8NrYQH4CPMRLdRhVyQV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arbazyousuf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
